language: cpp

script:
- cmake -H. -B_build 
- cmake --build _build
- cmake --build _build --target demo

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
